theme: jekyll-theme-tactile
title: Machine Learning for CICY 3-folds
description: Predicting Hodge numbers using Deep Learning
logo: /img/conv_inception.png
show_downloads: true
github:
  zip_url: https://github.com/thesfinox/ml-cicy/zipball/master
  tar_url: https://github.com/thesfinox/ml-cicy/tarball/master
